# Generated by Django 3.1 on 2020-10-11 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='logo_image',
            field=models.ImageField(blank=True, default='pizzariaImages/pizzalogo.png', upload_to='pizzariaImages'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('image_title', models.CharField(blank=True, max_length=120)),
                ('uploded_at', models.DateTimeField(auto_now_add=True)),
                ('pizzeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzeriaImages', to='stores.pizzeria')),
            ],
            options={
                'ordering': ['-uploded_at'],
            },
        ),
    ]
