# Generated by Django 3.1 on 2020-10-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20201011_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pizzeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzeria_images', to='stores.pizzeria'),
        ),
    ]
